# vim:ft=toml.chezmoitmpl

[settings]
experimental = false
cache_prune_age = "14d"
disable_hints = [ "python_multi", "python_precompiled" ]

[tools]
"cargo:cargo-binstall"  = "latest"
"cargo:cargo-cache"     = "latest"
"cargo:cargo-nextest"   = "latest"
"cargo:cargo-generate"  = "latest"
"cargo:adrs"            = "latest"
go                      = "latest"
lua                     = "latest"
prek                    = "latest"
rust                    = "latest"
usage                   = "latest"
